### ISSUE TITLE
Error on `make`

### ISSUE THREAD

**Issue by gazlaws-dev** [itsfarseen/dear-Board#1]
```
gui_main.cpp:92:48: error: format not a string literal and no format arguments [-Werror=format-security]
                 ImGui::Text(board.title.c_str());

```

**Comment by itsfarseen** [comment]
I had forgotten to push some commits. 
I hope it's fixed now. Builds here without errors.

**Comment by itsfarseen** [comment]
Basic usage:
Double click inside the empty window to create a board.
Double click inside a board to create a list entry.
Double click list entry to edit, Ctrl+Enter to finish editing.
Right click list entry/board for more options.

**Comment by itsfarseen** [comment]
Ubuntu, RedHat and some other distros have `-Wformat-security` flag enabled by default.
Since the Makefile also contains `-Werror`, this caused the compilation to fail.

006e1b1 hopefully fixes this
